USE [master]
GO

/****** Object:  Database [Jira]    Script Date: 9/13/2019 9:43:44 PM ******/
CREATE DATABASE [Jira]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Jira', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Jira.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Jira_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Jira_log.ldf' , SIZE = 270336KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Jira] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Jira].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Jira] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Jira] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Jira] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Jira] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Jira] SET ARITHABORT OFF 
GO

ALTER DATABASE [Jira] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Jira] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Jira] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Jira] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Jira] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Jira] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Jira] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Jira] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Jira] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Jira] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Jira] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Jira] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Jira] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Jira] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Jira] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Jira] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Jira] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Jira] SET RECOVERY FULL 
GO

ALTER DATABASE [Jira] SET  MULTI_USER 
GO

ALTER DATABASE [Jira] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Jira] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Jira] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Jira] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Jira] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Jira] SET QUERY_STORE = OFF
GO

USE [Jira]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Jira] SET  READ_WRITE 
GO


